# Config format schema number
format_version: 4

###################
## Model options
model_params:
  grid_size:
    - 480
    - 64
    - 32

  fea_dim: 9
  ppmodel_init_dim: 32
  use_norm: True
  dropout: 0.5

  use_co_attention: True  # use co-attention gate


###################
## Data_loader options
data_loader:
  data_path: "/media/ubuntu/4T/xjp/Livox/sipailou"
  return_ref: True  # reflectivity(intensity)
  residual: 8  # residual 1-8, 0 for none
  residual_path: "/home/ubuntu/data/Sipailou/mos/residual-sequential-480-64"
  batch_size: 64
  shuffle: True
  drop_few_static_frames: False  # drop_few_static_frames for training, speed up training while slightly reduce the accuracy
  num_workers: 4  # Set to four times the number of available GPUs

  dataset_type: "polar-livox"
  ignore_label: 255
  fixed_volume_space: True

  rotate_aug: False
  flip_aug: True
  transform_aug: True


###################
## Train params
train_params:
  name: "MotionBEV-livox"  # 取一个名字
  model_load_path: "/home/ubuntu/Desktop/MotionBEV/pretrain/MotionBEV-amcm-livox-val-89.22.pt"
  checkpoint_every_n_steps: 100
  max_num_epochs: 100
  eval_every_n_steps: 264
  learning_rate: 0.01
  optimizer: "SGD" # "SGD" "Adam" "AdamW"
  weight_decay: 0.0001   # weight decay
  momentum: 0.9          # sgd momentum
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  lr_decay: 0.95         # learning rate decay per epoch after initial cycle (from min lr)
